spring.application.name=task-scheduler

# Server Port
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/taskscheduler
spring.datasource.username=root
spring.datasource.password=root123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Quartz Configuration
spring.quartz.job-store-type=memory
spring.quartz.auto-startup=true

springdoc.swagger-ui.operationsSorter=method
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.muthu.task_scheduler